Замена на map. Фильтрация по диапазону
js-tasks-ru/jsbasic-20230727_alex012 pull request #6
Opened 2023-08-15 18:54 UTC by Alexpad25

2023-08-16 07:55 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-08-16 07:57 UTC, koalex requested changes
Нужно решить **3-3** и **3-5** т.к. эти задачи добавлены, но не решены

2023-08-27 17:26 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2023-08-28 05:50 UTC, koalex approved these changes

2023-08-28 05:50 UTC, merged